runner:
  visualize: false
  select_high_confidence: true
  train_recomposer_examplar: false
  threshold_lba: false
  random_frame: false
  num_sub_qa_generate: 3
  num_sub_qa_select: 1
  recomposer_name: Salesforce/blip2-flan-t5-xl
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /data2/
  device_map: cuda:0
  batch_size: 32
  output_dir: output/
  print_freq: 50
  use_vqa_tool: false
  num_bin: 50
  num_heatmap_row: 10
  debug: false
  cfg_pkl_path: SeViLA/cfg.pkl
datasets:
  dataset_name: VQA_Introspect
  num_data: -1
  split: val
  supple_n: 3
  data_type: images
  vqa_acc: true
  ann_paths:
    train:
    - /data1/VQA-Introspect/VQAIntrospect_trainv1.0.json
    - /data1/VQA/v2/v2_mscoco_train2014_annotations.json
    val:
    - /data1/VQA-Introspect/VQAIntrospect_valv1.0.json
    - /data1/VQA/v2/v2_mscoco_val2014_annotations.json
  vis_root: /data1/coco/images/
model:
  cache_dir: /data2/
dataset_name: VQA_Introspect
num_data: -1
