

datasets:
  data_type: images # [images|videos|features]
  vqa_acc: True
  ann_paths:
    train:
      - 'aokvqa/annotations/aokvqa_v1p0_train.json'
    val:
      - 'aokvqa/annotations/aokvqa_v1p0_val.json'
    # test:
    #   - 'aokvqa/annotations/aokvqa_v1p0_test.json'

  vis_root: 'coco/images/'
