

datasets:
  data_type: videos # [images|videos|features]
  n_frms: 4
  vqa_acc: False
  ann_paths:
    train:
      - AnotherMissOh/AnotherMissOhQA_train_set.json
    val:
      - AnotherMissOh/AnotherMissOhQA_val_set.json
      - AnotherMissOh/sub_qas_val_xl_fewshot_vqaintrospect_unique.json # created by xl
      # - AnotherMissOh/sub_qas_val_xl_fewshot_vqaintrospect_unique_N10.json # created by xl
      # - AnotherMissOh/sub_qas_val_chatgpt.json # created by gpt
      # - AnotherMissOh/sub_qas_val_xl.json # created by xl
      # - AnotherMissOh/sub_qas_val_xl_Ktype.json # created by xl, Ktype
  
  vis_root: AnotherMissOh/images/
  # vis_root: AnotherMissOh/AnotherMissOh_videos/total/
  only_scene: False
