

datasets:
  data_type: videos # [images|videos|features]
  n_frms: 4
  vqa_acc: False
  ann_paths:
    train:
      - MSRVTTQA/sevila_style/train.json
    val:
      - MSRVTTQA/sevila_style/val.json
      # - MSRVTTQA/sub_questions_val.json # created by gpt
      # - MSRVTTQA/sub_qas_val.json # created by gpt
      - MSRVTTQA/sub_qas_val_fewshot_vqaintrospect_unique.json # created by xl
      # - MSRVTTQA/sub_qas_val_xl.json # created by xl
      # - MSRVTTQA/sub_qas_val_xl_Ktype.json # created by xl, Ktype
  
  vis_root: MSRVTTQA/videos/
