

datasets:
  data_type: videos # [images|videos|features]
  n_frms: 4
  vqa_acc: False
  open_ended: True
  ann_paths:
    train:
      - MSVDQA/qa/train_qa.json
      - MSVDQA/youtube_mapping.txt
    val:
      - MSVDQA/qa/val_qa.json
      - MSVDQA/youtube_mapping.txt
      - MSVDQA/sub_qas_val_xl_fewshot_vqaintrospect_unique.json # created by xl
      # - MSVD/sub_qas_val_xl_fewshot_vqaintrospect_unique_N10.json # created by xl
      # - MSVD/sub_qas_val_chatgpt.json # created by gpt
      # - MSVD/sub_qas_val_xl.json # created by xl
      # - MSVD/sub_qas_val_xl_Ktype.json # created by xl, Ktype
  
  vis_root: MSVDQA/YouTubeClips/
