

datasets:
  data_type: videos # [images|videos|features]
  n_frms: 4
  vqa_acc: False
  ann_paths:
    train:
      - NExT_QA/sevila_style/train.json
    val:
      - NExT_QA/sevila_style/val.json
      - NExT_QA/sub_qas_val_xl_fewshot_vqaintrospect_unique.json # created by xl
      # - NExT_QA/sub_qas_val_xl_fewshot_vqaintrospect_unique_N10.json # created by xl
      # - NExT_QA/sub_qas_val_chatgpt.json # created by gpt
      # - NExT_QA/sub_qas_val_xl.json # created by xl
      # - NExT_QA/sub_qas_val_xl_Ktype.json # created by xl, Ktype
  
  vis_root: NExT_QA/NExTVideo/
