

datasets:
  data_type: images # [images|videos|features]
  vqa_acc: True
  ann_paths:
    train:
      - 'okvqa/annotations/okvqa_train.json'
    val:
      - 'okvqa/annotations/vqa_val_eval.json'
    # test:
    #   - 'okvqa/annotations/aokvqa_v1p0_test.json'

  vis_root: 'coco/images/'
