

datasets:
  data_type: images # [images|videos|features]
  vqa_acc: True
  ann_paths:
    train:
      - 'OKVQA/annotations/okvqa_train.json'
    val:
      - 'OKVQA/annotations/vqa_val_eval.json'
      - 'OKVQA/sub_qas_val_xl_fewshot_vqaintrospect_unique.json'

  vis_root: 'coco/images/'
