

datasets:
  data_type: videos # [images|videos|features]
  n_frms: 4
  vqa_acc: False
  ann_paths:
    train:
      - TVQA/sevila_style/train.json
    val:
      - TVQA/sevila_style/val.json
      # - TVQA/sub_questions_val.json # created by gpt
      # - TVQA/sub_qas_val.json # created by gpt
      - TVQA/sub_qas_val_xl_fewshot_vqaintrospect_unique.json # created by xl
      # - TVQA/sub_qas_val_xl.json # created by xl
      # - TVQA/sub_qas_val_xl_Ktype.json # created by xl, Ktype
  
  vis_root: TVQA/frames_hq/
