runner:
  visualize: false
  sub_mode: subqa
  select_high_confidence: true
  examplar: default
  threshold_lba: false
  vision_supple: false
  use_pre_generated_sub_q: true
  use_pre_generated_sub_a: true
  num_sub_qa_generate: 5
  num_sub_qa_select: 1
  num_frame_sampling: 3
  recomposer_name: llava-hf/llava-v1.6-mistral-7b-hf
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /model/
  device_map: cuda
  qwen_prompt: false
  max_new_tokens_subq: 100
  max_new_tokens_suba: 100
  max_new_tokens_maina: 256
  batch_size: 1
  seed: 44
  output_dir: output/
  print_freq: 20
  use_vqa_tool: false
  num_bin: 20
  num_heatmap_row: 10
  debug: false
  sevila_cfg_pkl_path: SeViLA/cfg.pkl
  flipped_vqa_cfg_pkl_path: flipped_vqa/cfg.pkl
datasets:
  dataset_name: MMMU
  root_dir: /data/
  num_data: 8
  split: val
  data_type: images
  vqa_acc: false
  ann_paths:
    val:
    - MMMU/MMMU
    - /data/MMMU/sub_qas_val_hf_fewshot_vqaintrospect_unique.json
  vis_root: dummy_vis_path
model:
  cache_dir: /model/
dataset_name: MMMU
num_data: 8
