runner:
  visualize: false
  match1ok: false
  select_high_confidence: false
  recomposer_examplar: true
  recomposer_name: Salesforce/blip2-flan-t5-xl
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /data2/
  device_map: false
  batch_size: 4
  output_dir: output/
  print_freq: 50
  use_vqa_tool: false
  num_bin: 50
  cfg_pkl_path: SeViLA/cfg.pkl
datasets:
  dataset_name: DramaQA
  num_data: -1
  split: val
  data_type: videos
  n_frms: 5
  vqa_acc: false
  only_scene: false
  ann_paths:
    train:
    - /data1/AnotherMissOh/AnotherMissOhQA_train_set.json
    - /data1/flipped_vqa/dramaqa/clipvitl14.pth
    val:
    - /data1/AnotherMissOh/AnotherMissOhQA_val_set.json
    - /data1/flipped_vqa/dramaqa/clipvitl14.pth
  vis_root: /data1/AnotherMissOh/images/
  vis_processor:
    train:
      name: alpro_video_train
      n_frms: 5
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
    eval:
      name: alpro_video_eval
      n_frms: 5
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
  text_processor:
    train:
      name: blip_question
    eval:
      name: blip_caption
model:
  cache_dir: /data2/
dataset_name: DramaQA
