runner:
  visualize: false
  sub_mode: subqa
  select_high_confidence: true
  train_recomposer_examplar: false
  threshold_lba: false
  random_frame: false
  num_sub_qa_generate: 1
  num_sub_qa_select: 1
  recomposer_name: Salesforce/blip2-flan-t5-xxl
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /data2/
  device_map: cuda:0
  batch_size: 4
  seed: 44
  output_dir: output/
  print_freq: 50
  use_vqa_tool: false
  num_bin: 50
  num_heatmap_row: 10
  conf_gap: 0.1
  debug: false
  cfg_pkl_path: SeViLA/cfg.pkl
datasets:
  dataset_name: STAR
  root_dir: /data1/
  num_data: -1
  split: val
  n_supple: 3
  data_type: videos
  n_frms: 4
  vqa_acc: false
  ann_paths:
    train:
    - STAR/sevila_style/train.json
    val:
    - STAR/sevila_style/val.json
  vis_root: STAR/videos_480/
  vis_processor:
    train:
      name: blip_video_eval
      n_frms: 4
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
    eval:
      name: blip_video_eval
      n_frms: 4
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
  text_processor:
    train:
      name: blip_question
    eval:
      name: blip_caption
model:
  cache_dir: /data2/
dataset_name: STAR
num_data: -1
n_frms: 4
