runner:
  visualize: false
  sub_mode: subqa
  select_high_confidence: false
  train_recomposer_examplar: false
  threshold_lba: false
  vision_supple: false
  use_pre_generated_sub_q: false
  use_pre_generated_sub_a: false
  num_sub_qa_generate: 1
  num_sub_qa_select: 1
  num_frame_sampling: 3
  recomposer_name: Salesforce/blip2-flan-t5-xl
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /data2/
  device_map: cuda:0
  batch_size: 16
  seed: 44
  output_dir: output/
  print_freq: 50
  use_vqa_tool: false
  num_bin: 50
  num_heatmap_row: 10
  debug: false
  sevila_cfg_pkl_path: SeViLA/cfg.pkl
  flipped_vqa_cfg_pkl_path: flipped_vqa/cfg.pkl
datasets:
  dataset_name: VLEP
  root_dir: /data1/
  num_data: -1
  split: val
  data_type: videos
  n_frms: 4
  vqa_acc: false
  ann_paths:
    train:
    - VLEP/sevila_style/train.json
    val:
    - VLEP/sevila_style/val.json
    - VLEP/sub_questions_val.json
  vis_root: VLEP/vlep_frames/
  vis_processor:
    train:
      name: blip_video_eval
      n_frms: 4
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
    eval:
      name: blip_video_eval
      n_frms: 4
      image_size: 224
      min_scale: 0.9
      max_scale: 1.0
  text_processor:
    train:
      name: blip_question
    eval:
      name: blip_caption
model:
  cache_dir: /data2/
dataset_name: VLEP
num_data: -1
