runner:
  visualize: false
  sub_mode: subqa
  select_high_confidence: true
  train_recomposer_examplar: false
  threshold_lba: false
  vision_supple: false
  use_pre_generated_sub_q: true
  use_pre_generated_sub_a: true
  num_sub_qa_generate: 5
  num_sub_qa_select: 5
  num_frame_sampling: 3
  recomposer_name: Salesforce/blip2-flan-t5-xl
  decomposer_name: self
  answerer_name: Salesforce/blip2-flan-t5-xl
  HF_HOME: /model/
  device_map: cuda:0
  batch_size: 32
  seed: 44
  output_dir: output/
  print_freq: 50
  use_vqa_tool: false
  num_bin: 20
  num_heatmap_row: 10
  debug: false
  sevila_cfg_pkl_path: SeViLA/cfg.pkl
  flipped_vqa_cfg_pkl_path: flipped_vqa/cfg.pkl
datasets:
  dataset_name: AOKVQA
  root_dir: /data/
  num_data: -1
  split: val
  data_type: images
  vqa_acc: true
  ann_paths:
    train:
    - AOKVQA/annotations/aokvqa_v1p0_train.json
    val:
    - AOKVQA/annotations/aokvqa_v1p0_val.json
    - AOKVQA/sub_qas_val_xl_fewshot_vqaintrospect_unique.json
  vis_root: coco/images/
model:
  cache_dir: /model/
dataset_name: AOKVQA
num_data: -1
