dataset:
  dataset_name: DramaQA
  data_type: image # [text|image|video|feature]
  question_type: multiple_choice # [open_ended|multiple_choice|both]
  vqa_acc: False
  # tau2: 0.10

  prompt:
    add_base_prompt: True
  
  vis_root: /data/DramaQA/AnotherMissOh_videos/total/ # [None|huggingface|vis_path]
  limit_mm_per_prompt: {image: 7}

  ann_paths:
    # train:
    #   - DramaQA/AnotherMissOhQA_train_set.json # 18465
    # val:
    #   - DramaQA/AnotherMissOhQA_val_set.json # 3889
    test:
      - DramaQA/AnotherMissOhQA_val_set.json # 3889

    # original: test: 4019
  